version: '3'        #Chnage the version to appropriate one as per your environment

volumes:
  nextcloud:
  db:
# This uses apache and Mariadb
services:
  db:
    image: mariadb      #There is an issue with "latest" mariadb image so I had to downgrade a version and choose 10.5 instead
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=        #Enter password of your choice here
      - MYSQL_PASSWORD=             #Enter password of your choice here
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=             #Enter password of your choice here
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
